import Link from "next/link";

type Variant = { href: string; label: string };

/**
 * "Para sua função" cross-link block rendered on canonical use-case pages.
 * Sends visible internal-link signal to the persona-specific variants
 * generated by the programmatic SEO data.
 */
export function PersonaVariantsSection({
  variants,
  intro,
}: {
  variants: Variant[];
  intro?: string;
}) {
  if (variants.length === 0) return null;
  return (
    <section className="space-y-4">
      <h2 className="font-display text-heading font-semibold text-midnight-ink">
        Pro seu papel
      </h2>
      <p className="text-body text-charcoal-text">
        {intro ??
          "Cada papel olha pra coisas diferentes no mesmo documento. Abre a versão pensada pra você:"}
      </p>
      <ul className="grid gap-3 sm:grid-cols-2">
        {variants.map((v) => (
          <li key={v.href}>
            <Link
              href={v.href}
              className="block rounded-lg border border-subtle-gray bg-crisp-white p-card-compact transition-colors hover:border-midnight-ink"
            >
              <span className="font-display text-body font-semibold text-midnight-ink">
                {v.label}
              </span>
              <span className="ml-2 text-faded-stone" aria-hidden="true">
                →
              </span>
            </Link>
          </li>
        ))}
      </ul>
    </section>
  );
}
